### ISSUE TITLE
nvdla_compiler doesn't work

### ISSUE THREAD

**Issue by HKLee2040** [nvdla/sw#4]
nvdla_compiler seems doesn't work

# ./nvdla_compiler -prototxt deploy.prototxt -caffemodel bvlc_alexnet.caffemodel -o /media/rogers/DATA/work/nvdla/vp
./nvdla_compiler: line 1: ELF: not found
./nvdla_compiler: line 2: syntax error: unexpected "("
#

**Comment by prasshantg** [comment]
Please share more details such as platform where are you testing it? steps you followed?

**Comment by HKLee2040** [comment]
I use prebuilt linux released in your package.
First, I copy the required file into nvdla/vp
Then
export SC_SIGNAL_WRITE_CHECK=DISABLE
./build/bin/aarch64_toplevel -c conf/aarch64_nvdla.lua
login  root, nvdla
and type the following command
./nvdla_compiler -prototxt deploy.prototxt -caffemodel bvlc_alexnet.caffemodel -o /media/rogers/DATA/work/nvdla/vp

**Comment by HKLee2040** [comment]
If I execute nvdla_compiler on PC side, it shows following message.
./nvdla_compiler: error while loading shared libraries: libnvdla_compiler.so: cannot open shared object file: No such file or directory
However, libnvdla_compiler.so exists in the same folder.

**Comment by wujunning2011** [comment]
Please add the lib nvdla_compiler.so PATH to LD_LIBRARY_PATH

$ echo $LD_LIBRARY_PATH
$ LD_LIBRARY_PATH=/usr/local/lib
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/nvdla/NVDLA/git-nvdla-sw/prebuilt/linux/
$ export LD_LIBRARY_PATH

**Comment by HKLee2040** [comment]
Thanks.  But I got new error message shown as below:

./nvdla_compiler: symbol lookup error: /media/rogers/DATA/work/nvdla/sw/prebuilt/linux/libnvdla_compiler.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

What package do I need to install?

**Comment by wujunning2011** [comment]
sorry, I did not faced with this problem.

here is the log info:

nvdla@nvdla:~/NVDLA/git-nvdla-sw/prebuilt/linux$ ./nvdla_compiler --prototxt alexnet/bvlc_alexnet/deploy.prototxt --caffemodel alexnet/bvlc_alexnet.caffemodel -o alexnet/
creating new wisdom context...
opening wisdom context...
parsing caffe network...
Marking output [0] for layer prob
attaching parsed network to the wisdom...
compiling profile "default"...
libnvdla<3> compile network
libnvdla<3> compile201
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
profile compiled "default"...
closing wisdom context...

**Comment by HKLee2040** [comment]
@wujunning2011  May I know your gcc version and OS version?

**Comment by wujunning2011** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
@HKLee2040

**Comment by HKLee2040** [comment]
OK, I try to get back to gcc 4.9.4, the problem still happens.
It seems not to be gcc issue.

**Comment by HKLee2040** [comment]
Is there any wrong library?

$ ldd nvdla_compiler 
	linux-vdso.so.1 =>  (0x00007ffe13138000)
	libnvdla_compiler.so => /media/rogers/DATA/work/nvdla/sw/prebuilt/linux/libnvdla_compiler.so (0x00007f49145df000)
	libprotobuf.so.9 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.9 (0x00007f49142a7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4913f1e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4913d07000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f491393d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4913633000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4913416000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f49131fc000)
	/lib64/ld-linux-x86-64.so.2 (0x000055678e83f000)

$ ldd libnvdla_compiler.so 
	linux-vdso.so.1 =>  (0x00007ffdde5e9000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff3fc031000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff3fbd28000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff3fbb10000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff3fb746000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d65a95e000)

**Comment by blueardour** [comment]
I also met the problem. It seems like a problem caused by the google protobuf.
Maybe the libproto version on our machine is not compatiable with that compiling the nvdla_compiler.

So,

**Comment by blueardour** [comment]
@wujunning2011 

Would you help to check:
`objdump -Tt //usr/lib/x86_64-linux-gnu/libprotobuf.so.9 | grep _ZNK6google8protobuf7Message11GetTypeNameEv
`
It reported nothing on my machine

**Comment by wujunning2011** [comment]
@blueardour 

At first, after installed Anaconda, the version of Protocol Buffer is so.14, so I uninstalled the newer version, and Reinstall the v2.6.1 version Protocol Buffer, which is so.9.

So, you can solve the version problem according this method.

**Comment by HKLee2040** [comment]
Unfortunately, wujunning2011's method doesn't work for me.  I use ubuntu 16.04, the default version of protocol buffer is 2.6.1.
I remove the default libprotobuf and reinstall it, but it's still not working.
There is a function named _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev instead of _ZNK6google8protobuf7Message11GetTypeNameEv in the libprotobuf.so.9.

**Comment by HKLee2040** [comment]
Back to ubuntu 14.04, re-build and install libprotobuf9, the problem is solved.

**Comment by blueardour** [comment]
I also successfully ran the nvdla_compiler in Ubuntu16.04.
Just install g++-4.9 and use this version of g++ to recompile the libprotobuf version 2.6.1.

Default g++5 came up with _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev instead of the desired _ZNK6google8protobuf7Message11GetTypeNameEv.

I compiled the Alexnet normally. However, when I tried other networks, most of then faild.

For VGG16, it gives:
`creating new wisdom context...
opening wisdom context...
parsing caffe network...
Marking output [0] for layer fc8
attaching parsed network to the wisdom...
compiling profile "default"...
libnvdla<3> compile network
libnvdla<3> compile201
Floating point exception (core dumped)
`

and in dmesg:
`[7348414.017475] traps: nvdla_compiler[25130] trap divide error ip:7f12922b1823 sp:7ffc6a523660 error:0 in libnvd
`

For googlenet, it gives:
`creating new wisdom context...
opening wisdom context...
parsing caffe network...
Marking output [0] for layer prob
attaching parsed network to the wisdom...
compiling profile "default"...
libnvdla<3> compile network
libnvdla<3> compile201
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
(DLA) Error 0x0000000b: Consumer of type CONVOLUTION already exists for node pdp-0 : conv-0  that is not connected via compute dependency to what we see now (in engine-ast/EngineNode.cpp, function resolveDataDependencies(), line 662)
(DLA) Error 0x0000000b:  conv-1, FIXME!!! (in engine-ast/EngineNode.cpp, function resolveDataDependencies(), line 663)
(DLA) Error 0x0000000b: (propagating from engine-ast/EngineGraph.cpp, function resolveDataDependencies(), line 794)
(DLA) Error 0x0000000b: (propagating from Compiler.cpp, function resolveDataDependencies(), line 1110)
(DLA) Error 0x00000008: failed compilation phase: resolveDataDependencies (propagating from Compiler.cpp, function compile(), line 3
(DLA) Error 0x00000004: compiler->compile("default") failed (in CompileTest.cpp, function compileProfile(), line 48)
(DLA) Error 0x00000004: (propagating from ParseTest.cpp, function parseAndCompile(), line 174)
(DLA) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 79)
`

**Comment by nvarnica** [comment]
I encountered the same issue when trying to compile GoogleNet.  Any resolution on this?

**Comment by redglass1984** [comment]
@Junning, I have already tried export LD_LIBRARY_PATH, but still can't run nvdla_complier
Can you give me some clue how to fix it?

shawn@shawn-System-Product-Name:~/nvdla$ export LD_LIBRARY_PATH=/home/shawn/nvdla/
shawn@shawn-System-Product-Name:~/nvdla$ ls
libnvdla_runtime.so  squeezenet_v1.1.caffemodel
nvdla_compiler       squeezenet_v1.1.prototxt
shawn@shawn-System-Product-Name:~/nvdla$ ./nvdla_compiler 
./nvdla_compiler: error while loading shared libraries: libnvdla_compiler.so: cannot open shared object file: No such file or directory
shawn@shawn-System-Product-Name:~/nvdla$ echo $LD_LIBRARY_PATH
/home/shawn/nvdla/

**Comment by zhouweiscut** [comment]
> > > ./nvdla_compiler -prototxt deploy.prototxt -caffemodel bvlc_alexnet.caffemodel -o /media/rogers/DATA/work/nvdla/vp
> > 
> > 
> > sorry , i have a basic question, where does the files 'deploy.protoext' and 'bvlc_alexnet.cafemodel' come from ?
> 
> It is part of a trained caffemodel, as described in http://caffe.berkeleyvision.org/model_zoo.html.
> 
> You can also download some of the trained models (with `.prototxt` and `.caffemodel`) from model zoo in the following link:
> https://github.com/BVLC/caffe/wiki/Model-Zoo
> 
> (search keyword '`prototxt`' or '`caffemodel`' in that page you will get the link to download files from varies models)

thank you, i got it.
